- hosts: k8s_master 
  become: yes 
  gather_facts: false 
  tasks:
    - name: get join command 
      shell: kubeadm token create --print-join-command 
      register: join_command_raw

    - name: Register dummy host with variable It Access In Next Play 
      add_host: 
        name: "DUMMY_HOST" 
        JOIN_COMMAND: "{{ join_command_raw.stdout }}"
        ansible_connection: local
- hosts: k8s_worker 
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['DUMMY_HOST']['JOIN_COMMAND'] }}>> node_joined.txt"  
      args:
        chdir: $HOME
        creates: node_joined.txt
