---
- name: Set executable permission for the script
  hosts: all
  tasks:
    - name: Set executable permission
      command: chmod +x ~/k8s_comman_dependencies.sh
    - name: Run the shell script
      shell: ~/k8s_comman_dependencies.sh
